### ISSUE TITLE
ujednolicenie formatu nazw rozdzialow

### ISSUE THREAD

**Issue by ghost** [piotrskurzynski/biblia#1272]
proponuję ujednolicić nazwy rozdziałów z formatu xx-... lub xxx-... dla psalmow do xxx-... dla uproszczenia programow korzystajacych z projekty, aby w niektorych przypadkach nie robic wyjatku dla psalmow

**Comment by piotrskurzynski** [comment]
Docelowo tekst będzie konwertowany na XML-a, JSON-a, lub inny przyjazny różnym programom format. W aktualnie używanych skryptach różna długość nazw nie wymaga definiowania wyjątków.
