### ISSUE TITLE
dodanie indexu nazw ksiąg

### ISSUE THREAD

**Issue by ghost** [piotrskurzynski/biblia#1273]
proponuje dodać indeksy nazw ksiag w folderze index, ktory zawieralby pliki kazdy z nazwami/opisami ksiag z roznych wydan biblii

**Comment by piotrskurzynski** [comment]
Poniższy format, można uzupełnić o nagłówki oraz dodatkowe pozycje, ale można też zaproponować inną formę.

"01-gen","GENESIS","Pierwsze Księgi Mojżeszowe","I. Mojżeszowe","Księga Rodzaju"
"02-exo","EXODUS","Wtóre Księgi Mojżeszowe","II. Mojżeszowe","Księga Wyjścia"
"03-lev","LEVITICUS","Trzecie Księgi Mojżeszowe","III. Mojżeszowe","Księga Kapłańska"
"04-num","NUMERI","Czwarte Księgi Mojżeszowe","IV. Mojżeszowe","Księga Liczb"
"05-deu","DEUTERONOMIUM","Piąte Księgi Mojżeszowe","V. Mojżeszowe","Księga Powtórzonego Prawa"
"06-jos","JOSUAE","Księga Jozuego","Jozuego","Księga Jozuego"
"07-jud","JUDICUM","Księga Sędziów","Sędziów","Księga Sędziów"
"08-rut","RUTH","Księga Ruty","Ruty","Księga Rut"
"09-reg","I REGUM","Pierwsza Księga Samuelowa","I. Samuelowa","I Księga Samuela"
"10-reg","II REGUM","Wtóra Księga Samuelowa","II. Samuelowa","II Księga Samuela"
"11-reg","III REGUM","I Księga Królewska","I. Królewska","I Księga Królewska"
"12-reg","IV REGUM","II Księga Królewska","II. Królewska","II Księga Królewska"
"13-par","I PARALIPOMENON","Pierwsza Księga Kroniki","I. Kroniki","I Księga Kronik"
"14-par","II PARALIPOMENON","Wtóra Księga Kroniki","II. Kroniki","II Księga Kronik"
"15-esd","I ESDRAE","Księga Ezdraszowa","Ezdraszowa","Księga Ezdrasza"
"16-esd","II ESDRAE","Księga Nehemiaszowa","Nehemiaszowa","Księga Nehemiasza"
"17-est","ESTHER","Księga Estery","Estery","Księga Estery"
"18-iob","IOB","Księga Ijobowa","Ijobowa","Księga Hioba"
"19-psa","PSALMI","Księga Psalmów","Psalmy","Księga Psalmów"
"20-pro","PROVERBIA SALOMONIS","Księga Przypowieści Salomonowych","Przypowieści Salomonowe","Księga Przysłów"
"21-ecc","ECCLESIASTES","Kaznodzieja Salomonowy","Kaznodzieja Salomonowy","Księga Kaznodziei"
"22-can","CANTICUM CANTICORUM","Pieśń nad Pieśniami Salomonowa","Pieśń Salomonowa","Pieśni nad Pieśniami"
"23-esa","ESAIAS","Proroctwo Izajaszowe","Izajasz","Księga Izajasza"
"24-ier","IEREMIAS","Proroctwo Jeremiaszowe","Jeremiasz","Księga Jeremiasza"
"25-lam","LAMENTATIONES IEREMIAE","Treny, to jest, Narzekania Jeremiaszowe","Treny Jeremiaszowe","Księga Lamentacji"
"26-eze","EZECHIEL","Proroctwo Ezechielowe","Ezechiel","Księga Ezechiela"
"27-dan","DANIEL","Proroctwo Danielowe","Daniel","Księga Daniela"
"28-ose","OSEAS","Proroctwo Ozeaszowe","Ozeasz","Księga Ozeasza"
"29-ioe","JOEL","Proroctwo Joelowe","Joel","Księga","Księga Joela"
"30-amo","AMOS","Proroctwo Amosowe","Amos","Księga","Księga Amosa"
"31-abd","ABDIAS","Proroctwo Abdiaszowe","Abdiasz","Księga","Księga Abdiasza"
"32-ion","IONAS","Proroctwo Jonaszowe","Jonasz","Księga","Księga Jonasza"
"33-mic","MICHEAS","Proroctwo Micheaszowe","Micheasz","Księga","Księga Micheasza"
"34-nah","NAHUM","Proroctwo Nahumowe","Nahum","Księga","Księga Nahuma"
"35-hab","HABACUC","Proroctwo Abakukowe","Abakuk","Księga","Księga Habakuka"
"36-sop","SOPHONIAS","Proroctwo Sofoniaszowe","Sofoniasz","Księga","Księga Sofoniasza"
"37-agg","AGGAEUS","Proroctwo Aggeuszowe","Aggeusz","Księga Aggeusza"
"38-zac","ZACHARIAS","Proroctwo Zachariaszowe","Zachariasz","Księga Zachariasza"
"39-mal","MALACHIAS","Proroctwo Malachiaszowe","Malachiasz","Księga Malachiasza"
"40-mat","MATTHAEUS","Ewangelia Według Świętego Mateusza","Ś. Mateusz","Ewangelia według świętego Mateusza"
"41-mar","MARCUS","Ewangelia Według Świętego Marka","Ś. Marek","Ewangelia Marka","Ewangelia według świętego Marka"
"42-luc","LUCAS","Ewangelia Według Świętego Łukasza","Ś. Łukasz","Ewangelia według świętego Łukasza"
"43-joh","JOHANNES","Ewangelia Według Świętego Jana","Ś. Jan","Ewangelia według świętego Jana"
"44-act","ACTA APOSTOLORUM","Dzieje Świętych Apostołów","Dzieje Apostolskie","Dzieje Apostolskie"
"45-rom","AD ROMANOS","List Świętego Pawła Apostoła Do Rzymian","Do Rzymian","List do Rzymian"
"46-cor","I AD CORINTHIOS","List Świętego Pawła Apostoła Do Koryntów Pierwszy","I. Do Koryntów","I List do Koryntian"
"47-cor","II AD CORINTHIOS","List Świętego Pawła Apostoła Do Koryntów Wtóry","II. Do Koryntów","II List do Koryntian"
"48-gal","AD GALATAS","List Świętego Pawła Apostoła Do Galatów","Do Galatów","List do Galatów"
"49-eph","AD EPHESIOS","List Świętego Pawła Apostoła Do Efezów","Do Efezów","List do Efezjan"
"50-phi","AD PHILIPPENSES","List Świętego Pawła Apostoła Do Filipensów","Do Filipensów","List do Filipian"
"51-col","AD COLOSSENSES","List Świętego Pawła Apostoła Do Kolosensów","Do Kolosensów","List do Kolosan"
"52-the","I AD THESSALONICENSES","List Świętego Pawła Apostoła Do Tesalonicensów Pierwszy","I. Do Tesalonicensów","I List do Tesaloniczan"
"53-the","II AD THESSALONICENSES","List Świętego Pawła Apostoła Do Tesalonicensów Wtóry","II. Do Tesalonicensów","II List do Tesaloniczan"
"54-tim","I AD TIMOTHEUM","List Świętego Pawła Apostoła Do Tymoteusza Pierwszy","I Do Tymoteusza","I List do Tymoteusza"
"55-tim","II AD TIMOTHEUM","List Świętego Pawła Apostoła Do Tymoteusza Wtóry","II Do Tymoteusza","II List do Tymoteusza"
"56-tit","AD TITUM","List Świętego Pawła Apostoła Do Tytusa","Do Tytusa","List do Tytusa"
"57-phi","AD PHILEMONEM","List Świętego Pawła Apostoła Do Filemona","Do Filemona","List do Filemona"
"58-heb","AD HEBRAEOS","List Świętego Pawła Apostoła Do Żydów","Do Żydów","List do Hebrajczyków"
"59-jac","EPISTOLA JACOBI","List Powszechny Świętego Jakuba","S. Jakuba","List Jakuba"
"60-pet","I PETRI","List Pierwszy Powszechny Świętego Piotra Apostoła","I. List Ś. Piotra","I List Piotra"
"61-pet","II PETRI","List Wtóry Powszechny Świętego Piotra Apostoła","II. List Ś. Piotra","II List Piotra"
"62-joh","I JOHANNIS","List Pierwszy Powszechny Świętego Jana Apostoła","I. List Ś. Jana","I List Jana"
"63-joh","II JOHANNIS","List Wtóry Świętego Jana Apostoła","II. List Ś. Jana","II List Jana"
"64-joh","III JOHANNIS","List Trzeci Świętego Jana Apostoła","III. List Ś. Jana","III List Jana"
"65-jud","JUDAS","List Powszechny Świętego Judasa","List Ś. Judasa","List Judy"
"66-apo","APOCALYPSIS","Objawienie Świętego Jana","Objawienie Ś. Jana","Objawienie Jana"
