### ISSUE TITLE
Apokryfy

### ISSUE THREAD

**Issue by rjolina** [piotrskurzynski/biblia#1279]
Czy jest planowane również dołączenie apokryfów tak jak w pierwszych wydaniach KJV?

i trochę offtop:
Gdzie można znaleźć bardziej czytelne skany BG, które zawierają apokryfy?

**Comment by piotrskurzynski** [comment]
Apokryfy nie są w planach.

Jeżeli istnieją skany czytelniejsze od tych podanych w pliku [info.md](https://github.com/piotrskurzynski/biblia/blob/main/info.md), to nic mi o nich nie wiadomo.

**Comment by piotrskurzynski** [comment]
Apokryfy nie są w planach.

Jeżeli istnieją skany czytelniejsze od tych podanych w pliku [info.md](https://github.com/piotrskurzynski/biblia/blob/main/info.md), to nic mi o nich nie wiadomo.
