### ISSUE TITLE
Ujednolicenie pisowni

### ISSUE THREAD

**Issue by UczenJezusa** [piotrskurzynski/biblia#1502]
Poniższe fragmenty mają niejednolitą pisownie:
1 Kron.3,5;14,4; 2 Sam.5,14.
Mimo to KJV też nie ma w tych miejscach jednolitej pisowni.

Słowo "ołtarz" w większości przypadków od I Mojżeszowej do Izajasza występuje z dużej litery.

1 Kron.23,10-11 "Zyna" i "Zyza"
1 Kron.6,17 i 1 Kron.23,7 - synowie Giersona mają różne imiona; KJV też ma różne wersje.
Syn Merarego - Musy lub Muzy; są 2 wersje; problem ten jest też w 1632, w KJV wszędzie jest to samo imię "Mushi"

Słowo - imię Maheli:
4 Moj.26,58 powinno być "dom Mahelitów"
1 Kron.6,47 np. zamiana na "Syna Mahelego"

**Comment by piotrskurzynski** [comment]
Ujednolicenie pisowni będzie miało miejsce podczas rewizji.
