### ISSUE TITLE
Aktualne cele projektu, aktualizacja prac wykonanych

### ISSUE THREAD

**Issue by Entis77** [piotrskurzynski/biblia#1786]
Proszę o aktualizację sprawdzonych rozdziałów - mam wrażenie, że się "troszkę" dublujemy. 
Ogólnie, proponuję zająć się wstępną korektą tekstu, który wcześniej nie był sprawdzany. Przyśpieszy to osiągnięcie pierwotnego celu.
W następnym kroku z przyjemnością mogę sprawdzić wszystko jeszcze raz.
Chyba, że zmieniły się cele...

**Comment by piotrskurzynski** [comment]
Plik zaktualizowany.
Cele pozostają bez zmian.
Dziękuję za zwrócenie uwagi.
